AGENT:

  TASK: 总结Mixture-of-Agents Enhances Large Language Model Capabilities论文里面的内容,并且说明作者,时间. 重点及论文的成果.
  RAG:
    MODULE_PATH: /mnt/c/Users/chenzi/Desktop/project/model/bce-embedding-base_v1
    PG_CONNECTION: postgresql+psycopg://langchain:langchain@localhost:6024/langchain
    COLLECTION_NAME: pdf
    IS_UPLOAD_FILE: true
    FILES_PATH:
      - /mnt/c/Users/chenzi/Desktop/project/data/Text-Animator Controllable Visual Text Video Generation.pdf
      - /mnt/c/Users/chenzi/Desktop/project/data/moa-llm.pdf
    ENCODING: utf-8
    CHUNK_SIZE: 256
    RAG_SEARCH_NUM: 4 # 数值越大 通过rag查询出来的结果越多 相应的内容也就越多


MODEL:
  MODEL_API_KEY:
  MODEL_NAME: gpt-4o
  MODEL_MAX_TOKENS: 2048

ENV:
  PROXY_URL: http://192.168.31.50:10890



































