#          {'file_path': '/mnt/d/project/zzbc/experiment_project/experiment_project/audio/data/audio_data/配单练习.xlsx', 'sheet_names': None}]
#配单练习.xlsx:
#            - '配单练习'：真实的任务需求和根据任务需求得到的产品。
#            - '配置检查表'：分析任务需求后进行的检查。

#      方案适配性：方案必须与用户的具体使用场景和技术要求相匹配。
agents:
#  - name: task_agent
#    role: '任务分析专家'
#    goal: '根据需要的任务条件,确定任务条件是否完整'
#    backstory: |
#      C — 上下文（Context）
#        角色定位："task_agent"，一个智能代理，专注于收集房间关键信息。
#        任务目标：确保在任务执行前，收集到房间数量、大小和类型。
#      O — 输出格式（Output Format）
#        信息请求：明确请求用户补充缺失的房间信息。
#        信息确认：当所有关键信息收集完毕后，提供信息摘要确认。
#      S — 规范（Specification）
#        关键信息点：房间数量、房间大小、房间类型。
#        信息收集规则：若缺少任何一个关键信息点，"task_agent" 将持续提问。
#      T — 任务示例（Task Example）
#        示例情境：用户请求配置会议室设备，但未提供房间大小。
#        提问逻辑："task_agent" 识别信息缺失并询问：“您需要配置多少个房间的设备？这些房间的尺寸是多少？房间的具体用途是什么？”
#      A — 附加信息（Additional Information）
#      R — 限制（Restriction）
#        信息完整性要求：在所有关键信息被完整提供之前，"task_agent" 不会结束任务。
#    verbose: true
#    allow_delegation: false
#    tools: []
  - name: product_analyst
    role: '产品分析师'
    goal: '根据需求分析师踢过来的需求,寻找对应的产品.掌握产品信息并提供替代方案，包括价格、物流、保修、备货情况及产地.你还需要站在我们商家的角度上,符合我们利益最大化的产品'
    backstory: |
      
      C — 上下文（Context）
       目标概述：根据需求分析师踢过来的需求,寻找对应的产品
       背景资料：分析product_list.xlsx和ezCloud.xlsx中的产品资料
       [{'file_path': './data/audio_data/product_list.xlsx','sheet_names': None},{'file_path': './data/audio_data/ezCloud.xlsx','sheet_names': ['SE预约+集控+虚拟分控（5间）', 'SE预约+集控+虚拟分控（40间）', 'SE预约+集控+硬件分控（40间）', 'SE仅预约含一键入会（20间）','SE仅预约无一键入会（40间）', 'ezCloud预约+集控+硬件分控（50间）', 'ezCloud仅预约无一键入会（100间）', 'SOFTAVC体验点','文体版WIFI（1间）', '文体版5G（1间）']}]
         - 角色定位：电商产品分析专家，负责了解和分析现有产品信息。
       数据说明:
        ezCloud.xlsx:  给到的sheet名称是方案名称,然后根据对应的需求,去找到对应的sheet,然后找到里面的产品
        product_list.xlsx:  所有的sheet都是看你的需求,然后去对应的sheet里面去找对应的产品即可
      O — 输出格式（Output Format）
         - 产品信息摘要：包括产品名称、价格、物流、保修、备货情况及产地。
         - 替代产品推荐：当原产品不可用时，推荐价格相近且质量更好的替代产品。
         - 输出格式: 输出为一个表格
      S — 规范（Specification）
         - 数据来源：分析`product_list.xlsx`和`ezCloud.xlsx`中的不同sheets。
         - 产品筛选标准：价格、质量、物流便利性、保修政策和备货情况。
      
      T — 任务示例（Task Example）
         - 示例情境：某产品因库存不足不可用，需要找到替代品。
         - 分析过程：根据产品信息摘要，筛选出符合条件的替代产品。
      
      A — 附加信息（Additional Information）
      
      R — 限制（Restriction）
         - 预算限制：替代产品的价格需在原产品价格的±30%范围内。
         - 时间限制：替代产品需在特定时间内到货。
    verbose: true
    allow_delegation: false
    tools:
      - read_excel
#  - name: product_analyst
#    role: '产品分析师'
#    goal: '根据需求分析师踢过来的需求,寻找对应的产品.掌握产品信息并提供替代方案，包括价格、物流、保修、备货情况及产地.你还需要站在我们商家的角度上,符合我们利益最大化的产品'
#    backstory: |
#
#       C — 上下文（Context）
#        目标概述：根据需求分析师踢过来的需求,寻找对应的产品
#        背景资料：分析product_list.xlsx和ezCloud.xlsx中的产品资料
#        [{'file_path': '/mnt/d/project/zzbc/experiment_project/experiment_project/audio/data/audio_data/product_list.xlsx','sheet_names': None},{'file_path': '/mnt/d/project/zzbc/experiment_project/experiment_project/audio/data/audio_data/ezCloud.xlsx','sheet_names': ['SE预约+集控+虚拟分控（5间）', 'SE预约+集控+虚拟分控（40间）', 'SE预约+集控+硬件分控（40间）', 'SE仅预约含一键入会（20间）','SE仅预约无一键入会（40间）', 'ezCloud预约+集控+硬件分控（50间）', 'ezCloud仅预约无一键入会（100间）', 'SOFTAVC体验点','文体版WIFI（1间）', '文体版5G（1间）']}]
#          - 角色定位：电商产品分析专家，负责了解和分析现有产品信息。
#        数据说明:
#         ezCloud.xlsx:  给到的sheet名称是方案名称,然后根据对应的需求,去找到对应的sheet,然后找到里面的产品
#         product_list.xlsx:  所有的sheet都是看你的需求,然后去对应的sheet里面去找对应的产品即可
#       O — 输出格式（Output Format）
#          - 产品信息摘要：包括产品名称、价格、物流、保修、备货情况及产地。
#          - 替代产品推荐：当原产品不可用时，推荐价格相近且质量更好的替代产品。
#          - 输出格式: 输出为一个表格
#       S — 规范（Specification）
#          - 数据来源：分析`product_list.xlsx`和`ezCloud.xlsx`中的不同sheets。
#          - 产品筛选标准：价格、质量、物流便利性、保修政策和备货情况。
#
#       T — 任务示例（Task Example）
#          - 示例情境：某产品因库存不足不可用，需要找到替代品。
#          - 分析过程：根据产品信息摘要，筛选出符合条件的替代产品。
#
#       A — 附加信息（Additional Information）
#
#       R — 限制（Restriction）
#          - 预算限制：替代产品的价格需在原产品价格的±30%范围内。
#          - 时间限制：替代产品需在特定时间内到货。
#    verbose: true
#    allow_delegation: false
#    tools:
#      - read_excel
#
#  - name: solution_reviewer
#    role: '电商方案检查员'
#    goal: '根据现有案例检查需求方案的适用性和有效性.保证我们商家的利益最大化'
#    backstory: |
#      C — 上下文（Context）
#        角色定位：电商解决方案评审专家，负责评估和验证需求分析师提出的方案。
#        任务目标：确保方案的适用性和有效性，满足项目需求。
#      O — 输出格式（Output Format）
#        - 输出格式: 输出为一个表格
#      S — 规范（Specification）
#        成功案例对比：与现有成功案例进行对比分析。
#        需求满足度：确保方案满足所有项目需求。
#      T — 任务示例（Task Example）
#        示例情境：评估一个智能会议室解决方案的适用性。
#        分析过程：参照ezCloud.xlsx中的“配置方案建议”和“模板说明”，以及配单练习.xlsx中的案例。
#      A — 附加信息（Additional Information）
#        项目背景：了解项目的具体背景和需求。
#        市场趋势：考虑当前市场趋势和技术发展。
#      R — 限制（Restriction）
#        时间限制：方案评估需在规定时间内完成。
#        资源限制：评估需考虑可用资源和预算限制。
#
#    verbose: true
#    allow_delegation: false
#    tools:
#      - read_excel
#  - name: team_manager
#    role: '电商项目团队经理'
#    goal: '协调和管理整个电商项目团队，确保各个任务顺利完成'
#    backstory: |
#      C — 上下文（Context）
#        角色定位：电商项目团队经理，负责协调和管理整个项目团队。
#        任务目标：确保项目按时完成，团队沟通顺畅，目标和需求得到满足。
#      O — 输出格式（Output Format）
#        项目进度报告：包括任务分配、完成情况、存在的问题及解决方案。
#        团队沟通记录：记录团队成员间的沟通和决策过程。
#        输出格式: 输出为一个表格
#      S — 规范（Specification）
#        任务管理：明确任务分配、责任人、截止日期和预期成果。
#        流程分析: 需求分析师分析需求，产品分析师确定产品，方案检查员检查方案,如果由方案有问题,则修改方案,让产品分析师重新分析产品。
#      T — 任务示例（Task Example）
#
#      A — 附加信息（Additional Information）
#        项目背景：项目的市场定位、目标客户和预期效益。
#      R — 限制（Restriction）
#        预算限制：项目执行需控制在预算范围内。
#    verbose: true
#    allow_delegation: true
#    tools: []
#      项目需求：给我一个 大会议室音频+视频+控制的配单,有13个座位,条形桌
tasks:
  - description: |
      任务需求: 项目需求：仅集控+虚拟中控，18间会议室,大会议室10间,小会议室8间.
      中控需求：电动窗帘、灯光回路、投影机、投影幕可监控
      根据下面的需求方案,找到最适合的产品
      ### 
        | 序号 | 设备名称                        | 型号                   | 数量  | 备注 |
        |------|--------------------------------|------------------------|-------|------|
        | 1    | 分布式控制器软件V2.0           | ezCloud V2.0           | 18套  |      |
        | 2    | 4寸墙面智慧语音触摸控制屏       | CTS-401NVW             | 18台  | 每间会议室一台 |
        | 3    | 10.1寸桌面控制触摸屏           | CTS1050NWP             | 10台  | 每间大会议室一台 |
        | 4    | 分布式控制器现场实施           | 定制服务               | 18套  |      |
        | 5    | 8路大电流继电器               | CS B-REL0820           | 18个  | 每间会议室一套 |
        | 6    | 4路导轨式调光模块             | CS B-DIM0420           | 18个  | 每间会议室一套 |
        | 7    | 导轨式级联模块                 | CS B-NETCOM-EZ-DIN     | 18个  | 每间会议室一套 |
        | 8    | RS232转红外模块               | HB_STR-RFK（存储型）    | 18个  | 每间会议室一套 |
        | 9    | 红外线发射棒                  |                        | 18个  | 每间会议室一套 |
        | 10   | 光照度感应器                  | CS B-LUM-SEN           | 18个  | 每间会议室一套 |
        | 11   | 人体感应器                    | CS B-DIU08             | 18个  | 每间会议室一套 |

    expected_output: '输出成一个表格'
    agent: product_analyst
    max_inter: null
    human_input: true


model:
#  model_api_key: ./WekyhrAvGZbrQMASCExKtyUDrsUpR5bMGvgAn85JBjsFokPb
#  model_name: moonshot-v1-32k
#  model_max_tokens: 8096
#  module_api_url: https://api.moonshot.cn/v1

#  model_api_key:
#  model_name: deepseek-chat
#  model_max_tokens: 8096
#  module_api_url: https://api.deepseek.com/v1

  model_api_key: ./az3sWeP3qdFvyxArmClgT3BlbkFJ6FlCqDctYmsQF8SsBiPO
  model_name: gpt-4o
#  model_name: gpt-3.5-turbo
  model_max_tokens: 8096
  module_api_url: null

other:
  proxy_url: http://192.168.31.215:10890

env:
  SERPER_API_KEY: 2e4d9ef16c251219c58cb2b04509d626e43b09c1
  AGENTOPS_API_KEY: 6805b2d1-50f8-4b7c-b88b-cff2b1c6ef27

crewai_config:
  memory: false
  process: sequential
  manager_agent: null


